"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup
import py2exe

APP = ['web2py.py']
DATA_FILES = ['admin.tar', 'examples.tar', 'welcome.tar',
              'ABOUT','LICENSE','VERSION','web2py.ico']

setup(
    console=APP,
    data_files=DATA_FILES,
)
