#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['web2py.py']
DATA_FILES = [
    'admin.tar',
    'examples.tar',
    'welcome.tar',
    'ABOUT',
    'LICENSE',
    'VERSION',
    ]
OPTIONS = {'argv_emulation': True}

setup(app=APP, data_files=DATA_FILES, options={'py2app': OPTIONS},
      setup_requires=['py2app'])
